Traceback (most recent call last):
  File "/home/niujh/csapp/OS_jyy/os-workbench-2022/crepl/plugin.py", line 20, in <module>
    main()
  File "/home/niujh/csapp/OS_jyy/os-workbench-2022/crepl/plugin.py", line 15, in main
    code = sys.stdin.readline()
OSError: [Errno 9] Bad file descriptor
